name: release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: set-time
        id: set_time
        run: |
          echo "RELEASE_NAME=build ${{ github.run_id }} - $(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "TAG_NAME=release-$(date +'%Y%m%d%H%M%S')-${{ github.run_id }}" >> $GITHUB_ENV

      - name: install
        run: npm install

      - name: build
        run: npm run build

      - name: zip
        run: zip -r release-artifact.zip ./index.html ./main.js ./sample.qasm

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          body: |
          files: |
            ./release-artifact.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
